# Generated by Django 5.2.7 on 2025-11-01 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('email_admin', models.EmailField(max_length=254, unique=True)),
                ('mdp_admin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('specialite', models.CharField(max_length=100)),
                ('annee_etude', models.CharField(max_length=10)),
            ],
        ),
    ]
