# Generated by Django 5.2.9 on 2026-01-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='can_create_any_course_content',
            field=models.BooleanField(default=False),
        ),
    ]
