# Generated by Django 5.2.7 on 2025-11-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='salt',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
