# Generated by Django 5.2.7 on 2025-12-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
