# Generated by Django 5.2.7 on 2025-11-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id_exercice', models.AutoField(primary_key=True, serialize=False)),
                ('titre_exo', models.CharField(max_length=255)),
                ('enonce', models.TextField()),
                ('niveau_exo', models.CharField(max_length=50)),
                ('visibilite_exo', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
