# Generated by Django 5.2.9 on 2025-12-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id_exercice', models.AutoField(primary_key=True, serialize=False)),
                ('titre_exo', models.CharField(max_length=255)),
                ('enonce', models.TextField()),
                ('niveau_exo', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('categorie', models.CharField(default='None', max_length=255)),
                ('visibilite_exo', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours')),
            ],
        ),
    ]
