# Generated by Django 5.2.8 on 2025-12-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
