# Generated by Django 6.0 on 2025-12-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='max_soumissions',
            field=models.PositiveIntegerField(default=0, help_text='0 = illimité. Sinon, nombre maximum de soumissions par étudiant.'),
        ),
    ]
