# Generated by Django 5.2.7 on 2025-12-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id_notif', models.AutoField(primary_key=True, serialize=False)),
                ('message_notif', models.TextField()),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_type', models.CharField(max_length=50)),
                ('module_source', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'feedback_notification',
                'ordering': ['-date_envoie'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id_feedback', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('etoile', models.PositiveSmallIntegerField()),
                ('afficher_nom', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-date_creation'],
            },
        ),
    ]
