# Generated by Django 5.2.7 on 2026-01-05 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0002_initial'),
        ('exercices', '0002_initial'),
        ('feedback', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackexercice',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_exercices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackexercice',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='exercices.exercice'),
        ),
        migrations.AddField(
            model_name='feedbackexercice',
            name='tentative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exercice', to='dashboard.tentativeexercice'),
        ),
        migrations.AddField(
            model_name='notification',
            name='admin_destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to='users.administrateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur_destinataire',
            field=models.ForeignKey(blank=True, db_column='utilisateur_destinataire_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur_envoyeur',
            field=models.ForeignKey(blank=True, db_column='utilisateur_envoyeur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['content_type', 'object_id'], name='feedback_content_25f1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='feedback_no_content_1777ae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur_destinataire', 'is_read'], name='feedback_no_utilisa_9df4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['admin_destinataire', 'is_read'], name='feedback_no_admin_d_de835d_idx'),
        ),
    ]
