# Generated by Django 5.2.7 on 2025-12-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='nom_personnel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]