# Generated by Django 5.2.7 on 2025-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackexercice',
            options={},
        ),
        migrations.AlterField(
            model_name='feedbackexercice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='feedbackexercice',
            table=None,
        ),
    ]
