# Generated by Django 5.2.7 on 2025-12-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_nom_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='nom_personnel',
        ),
        migrations.AddField(
            model_name='feedback',
            name='afficher_nom',
            field=models.BooleanField(default=False),
        ),
    ]
