# Generated by Django 5.2.7 on 2025-12-26 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('exercices', '0002_initial'),
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackExercice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='exercices.exercice')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dashboard.tentativeexercice')),
            ],
            options={
                'db_table': 'feedback_exercice',
                'ordering': ['-date_creation'],
            },
        ),
    ]
