# Generated by Django 5.2.8 on 2025-12-28 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dashboard', '0002_initial'),
        ('exercices', '0002_initial'),
        ('feedback', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackExercice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_exercice',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='admin_destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to='users.administrateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur_destinataire',
            field=models.ForeignKey(blank=True, db_column='utilisateur_destinataire_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['admin_destinataire', 'is_read'], name='feedback_no_admin_d_de835d_idx'),
        ),
        migrations.AddField(
            model_name='feedbackexercice',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackexercice',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='exercices.exercice'),
        ),
        migrations.AddField(
            model_name='feedbackexercice',
            name='tentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='dashboard.tentativeexercice'),
        ),
    ]
