# Generated by Django 5.2.7 on 2025-12-29 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedbackexercice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackexercice',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='feedbackexercice',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_exercices', to=settings.AUTH_USER_MODEL),
        ),
    ]
