# Generated by Django 5.2.8 on 2025-12-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        ('feedback', '0003_remove_feedback_nom_personnel_feedback_afficher_nom'),
    ]

    operations = [
    ]
