# Generated by Django 5.2.7 on 2025-12-26 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0003_feedbackexercice'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to='users.administrateur'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur_destinataire',
            field=models.ForeignKey(blank=True, db_column='utilisateur_destinataire_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_recues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['admin_destinataire', 'is_read'], name='feedback_no_admin_d_de835d_idx'),
        ),
    ]
