# Generated by Django 5.2.7 on 2025-12-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
        ('feedback', '0004_alter_feedbackexercice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackexercice',
            name='tentative',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_exercice', to='dashboard.tentativeexercice'),
        ),
    ]
