# Generated by Django 5.2.9 on 2025-12-28 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_qst', models.AutoField(primary_key=True, serialize=False)),
                ('texte_qst', models.TextField()),
                ('reponse_correcte', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercices.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id_option', models.AutoField(primary_key=True, serialize=False)),
                ('texte_option', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreMinimum', models.IntegerField()),
                ('activerDuration', models.BooleanField(default=True)),
                ('duration', models.DurationField(null=True)),
                ('nbMax_tentative', models.IntegerField(default=0)),
                ('delai_entre_tentatives', models.PositiveIntegerField(default=0)),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('score_total', models.FloatField(default=0)),
                ('terminer', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(null=True)),
                ('score_obtenu', models.FloatField(default=0)),
                ('option_choisie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('reponse_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='quiz.reponsequiz')),
            ],
        ),
    ]
