# Generated by Django 5.2.7 on 2025-12-18 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_qst', models.AutoField(primary_key=True, serialize=False)),
                ('texte_qst', models.TextField()),
                ('reponse_correcte', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exercices.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id_option', models.AutoField(primary_key=True, serialize=False)),
                ('texte_option', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreMinimum', models.IntegerField()),
                ('activerDuration', models.BooleanField(default=True)),
                ('duration', models.DurationField(null=True)),
                ('nbMax_tentative', models.IntegerField(default=0)),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice')),
            ],
        ),
    ]
