# Generated by Django 5.2.8 on 2025-12-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_qst', models.AutoField(primary_key=True, serialize=False)),
                ('texte_qst', models.TextField()),
                ('reponse_correcte', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id_option', models.AutoField(primary_key=True, serialize=False)),
                ('texte_option', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreMinimum', models.IntegerField()),
                ('exercice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice')),
            ],
        ),
    ]
