# Generated by Django 5.2.8 on 2025-12-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='activerDuration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='nbMax_tentative',
            field=models.IntegerField(default=0),
        ),
    ]
