# Generated by Django 5.2.7 on 2025-12-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_reponsequiz_reponsequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='delai_entre_tentatives',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
