# Generated by Django 5.2.7 on 2025-11-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
    ]
