# Generated by Django 5.2.7 on 2026-01-02 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('users', '0002_auto_20251231_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrateur'),
        ),
    ]
