# Generated by Django 5.2.8 on 2025-12-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_add_cible_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='cible',
            field=models.CharField(choices=[('etudiants', 'Étudiants'), ('enseignants', 'Enseignants')], max_length=20),
        ),
    ]
