# Generated by Django 5.2.7 on 2025-12-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='cible',
            field=models.CharField(choices=[('etudiants', 'Étudiants'), ('enseignants', 'Enseignants')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
