# Generated by Django 5.2.7 on 2025-12-07 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_commentaire_options_alter_forum_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-date_liker']},
        ),
        migrations.RemoveField(
            model_name='like',
            name='id',
        ),
        migrations.AddField(
            model_name='like',
            name='id_like',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MessageLike',
            fields=[
                ('id_message_like', models.AutoField(primary_key=True, serialize=False)),
                ('date_liker', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_likes', to='forum.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_liker'],
                'unique_together': {('message', 'utilisateur')},
            },
        ),
    ]
