# Generated by Django 5.2.8 on 2025-12-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
        ('forum', '0003_alter_forum_cible'),
    ]

    operations = [
    ]
