# Generated by Django 5.2.8 on 2026-01-04 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_administrateur_message_administrateur_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='messagelike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrateur'),
        ),
        migrations.AddField(
            model_name='like',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrateur'),
        ),
        migrations.AddField(
            model_name='messagelike',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrateur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagelike',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('forum', 'utilisateur'), name='unique_forum_like_utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('forum', 'administrateur'), name='unique_forum_like_admin'),
        ),
        migrations.AddConstraint(
            model_name='messagelike',
            constraint=models.UniqueConstraint(fields=('message', 'utilisateur'), name='unique_message_like_utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='messagelike',
            constraint=models.UniqueConstraint(fields=('message', 'administrateur'), name='unique_message_like_admin'),
        ),
    ]
