# Generated by Django 5.2.7 on 2026-01-04 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_message_administrateur_alter_message_utilisateur'),
        ('users', '0002_auto_20251231_0052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagelike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrateur'),
        ),
        migrations.AddField(
            model_name='messagelike',
            name='administrateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.administrateur'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagelike',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='messagelike',
            constraint=models.UniqueConstraint(fields=('message', 'utilisateur'), name='unique_message_like_utilisateur'),
        ),
        migrations.AddConstraint(
            model_name='messagelike',
            constraint=models.UniqueConstraint(fields=('message', 'administrateur'), name='unique_message_like_admin'),
        ),
    ]
