# Generated by Django 5.2.7 on 2025-12-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_like_options_alter_messagelike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='contenu_forum',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
