# Generated by Django 5.2.9 on 2025-12-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('exercices', '0002_initial'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacecour',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
        ),
        migrations.AddField(
            model_name='spacecour',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AddField(
            model_name='spaceetudiant',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spaceetudiant',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AddField(
            model_name='spaceexo',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice'),
        ),
        migrations.AddField(
            model_name='spaceexo',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AlterUniqueTogether(
            name='spacecour',
            unique_together={('space', 'cours')},
        ),
        migrations.AlterUniqueTogether(
            name='spaceetudiant',
            unique_together={('etudiant', 'space')},
        ),
        migrations.AlterUniqueTogether(
            name='spaceexo',
            unique_together={('space', 'exercice')},
        ),
    ]
