# Generated by Django 5.2.7 on 2026-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecour',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spaceexo',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
