# Generated by Django 5.2.9 on 2026-01-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacecour',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spaceexo',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
