# Generated by Django 5.2.8 on 2025-12-15 20:55

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avancement_cours', models.FloatField()),
                ('temps_passe', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TentativeExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateField()),
                ('heure_tentative', models.TimeField()),
                ('etat', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('temps_passe', models.DurationField()),
                ('reponse', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeconComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecon')),
            ],
        ),
        migrations.CreateModel(
            name='LeconComplete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecon')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'lecon')},
            },
        ),
    ]
