# Generated by Django 5.2.9 on 2025-12-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateField()),
                ('heure_tentative', models.TimeField()),
                ('etat', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('temps_passe', models.DurationField()),
                ('reponse', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avancement_cours', models.FloatField()),
                ('temps_passe', models.DurationField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours')),
            ],
        ),
    ]
