# Generated by Django 5.2.8 on 2025-12-18 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressioncours',
            name='avancement_cours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='progressioncours',
            name='temps_passe',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
