# Generated by Django 5.2.7 on 2025-12-29 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('dashboard', '0001_initial'),
        ('exercices', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leconcomplete',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressioncours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
        ),
        migrations.AddField(
            model_name='progressioncours',
            name='derniere_lecon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lecon'),
        ),
        migrations.AddField(
            model_name='progressioncours',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressionhistory',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
        ),
        migrations.AddField(
            model_name='progressionhistory',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='progressionhistory',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionduration',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tentativeexercice',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice'),
        ),
        migrations.AddField(
            model_name='tentativeexercice',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='leconcomplete',
            unique_together={('utilisateur', 'lecon')},
        ),
        migrations.AddConstraint(
            model_name='progressioncours',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'cours'), name='unique_user_cours'),
        ),
    ]
