# Generated by Django 5.2.7 on 2025-11-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('condition', models.CharField(help_text='Condition to earn this badge', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GagnerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.badge')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'badge')},
            },
        ),
    ]
