# Generated by Django 5.2.9 on 2025-12-18 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressioncours',
            name='temps_passe',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
