# Generated by Django 5.2.7 on 2025-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='categorie',
            field=models.CharField(default='Général', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='numpoints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='badge',
            name='condition',
            field=models.CharField(max_length=255),
        ),
    ]
