# Generated by Django 6.0 on 2025-12-26 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tentativeexercice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='tentativeexercice',
            unique_together=set(),
        ),
    ]
