# Generated by Django 5.2.9 on 2025-12-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncours',
            name='derniere_lecon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.lecon'),
        ),
    ]
