# Generated by Django 5.2.9 on 2025-12-18 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('dashboard', '0002_alter_progressioncours_temps_passe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='progressioncours',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'cours'), name='unique_user_cours'),
        ),
    ]
