# Generated by Django 6.0 on 2025-12-19 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativeexercice',
            name='date_soumission',
        ),
        migrations.RemoveField(
            model_name='tentativeexercice',
            name='heure_tentative',
        ),
        migrations.AddField(
            model_name='tentativeexercice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentativeexercice',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tentativeexercice',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('corrige', 'Corrigé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='tentativeexercice',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tentativeexercice',
            name='temps_passe',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
