# Generated by Django 6.0 on 2025-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_tentativeexercice_date_soumission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeexercice',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
