# Generated by Django 5.2.9 on 2025-12-16 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_progressioncours_derniere_lecon'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
