# Generated by Django 6.0 on 2025-12-28 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('dashboard', '0003_alter_tentativeexercice_options_and_more'),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressionhistory',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='progressionhistory',
            name='type_contenu',
            field=models.CharField(choices=[('cours', 'Cours'), ('quiz', 'Quiz')], default='cours', max_length=10),
        ),
        migrations.AlterField(
            model_name='progressionhistory',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
        ),
    ]
