# Generated by Django 5.2.7 on 2025-11-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_badge_categorie_badge_numpoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tentativeexercice',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
