# Generated by Django 6.0 on 2025-12-20 23:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tentativeexercice_output'),
        ('exercices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tentativeexercice',
            unique_together={('utilisateur', 'exercice')},
        ),
    ]
