# Generated by Django 5.2.8 on 2025-12-21 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tentativeexercice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressioncours',
            name='temps_passe',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
