# Generated by Django 5.2.8 on 2025-12-22 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_add_created_submitted_to_tentativeexercice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeexercice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 22, 21, 19, 33, 890982, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
