<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-17 16:15
=======
# Generated by Django 5.2.8 on 2025-12-15 20:55
>>>>>>> main

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('titre_cour', models.CharField(max_length=255)),
                ('niveau_cour', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('visibilite_cour', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('titre_section', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id_lecon', models.AutoField(primary_key=True, serialize=False)),
                ('titre_lecon', models.CharField(max_length=255)),
                ('contenu_lecon', models.TextField()),
                ('type_lecon', models.CharField(max_length=50)),
                ('ordre', models.IntegerField()),
<<<<<<< HEAD
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.section')),
=======
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('titre_section', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
>>>>>>> main
            ],
        ),
    ]
