# Generated by Django 5.2.9 on 2025-12-28 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id_cours', models.AutoField(primary_key=True, serialize=False)),
                ('titre_cour', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('niveau_cour', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('duration', models.DurationField()),
                ('visibilite_cour', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('titre_section', models.CharField(max_length=255)),
                ('ordre', models.IntegerField()),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id_lecon', models.AutoField(primary_key=True, serialize=False)),
                ('titre_lecon', models.CharField(max_length=255)),
                ('contenu_lecon', models.TextField()),
                ('type_lecon', models.CharField(max_length=50)),
                ('ordre', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.section')),
            ],
        ),
    ]
