# Generated by Django 5.2.7 on 2025-11-23 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercice',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exercice'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='exercice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.exercice'),
        ),
        migrations.AddField(
            model_name='section',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section'),
        ),
    ]
