# Generated by Django 5.2.7 on 2025-12-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_section_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.cours'),
        ),
    ]
