# Generated by Django 5.2.9 on 2025-12-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('courses', '0003_alter_lecon_section_alter_section_cours'),
    ]

    operations = [
    ]
