# Generated by Django 5.2.8 on 2025-12-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('courses', '0003_add_created_at_to_cours'),
    ]

    operations = [
    ]
