# Generated by Django 5.2.9 on 2025-12-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20251206_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecon',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.cours'),
        ),
    ]
