# Generated by Django 5.2.8 on 2025-12-21 21:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_0002_initial_0003_add_created_at_to_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
