<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-12-17 22:34

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.8 on 2025-12-15 20:55

import django.db.models.deletion
>>>>>>> main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercices', '0001_initial'),
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> main
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explication_ia', models.TextField()),
                ('date_analyse', models.DateField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercices.exercice')),
<<<<<<< HEAD
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
>>>>>>> main
            ],
        ),
    ]
