# Generated by Django 6.0 on 2025-12-30 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icone', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('condition', models.CharField(max_length=255)),
                ('categorie', models.CharField(default='Général', max_length=50)),
                ('numpoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GagnerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_obtention', models.DateField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.badge')),
            ],
        ),
    ]
