# Generated by Django 5.2.8 on 2026-01-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ajouter le champ sans default (temporairement nullable)
        migrations.AddField(
            model_name='gagnerbadge',
            name='utilisateur',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=True,
                blank=True,
            ),
        ),

        # Rendre le champ obligatoire une fois ajouté
        migrations.AlterField(
            model_name='gagnerbadge',
            name='utilisateur',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=False,
                blank=False,
            ),
        ),

        # Contrainte d’unicité
        migrations.AlterUniqueTogether(
            name='gagnerbadge',
            unique_together={('utilisateur', 'badge')},
        ),
    ]
